### ISSUE TITLE
What are the parameters when training the model ?

### ISSUE THREAD

**Issue by YZS-web** [soarsmu/iTiger#1]
Now I want to use the data of iTAPE to train the model of itiger from scratch. I will run the run_summarization.py file to achieve this operation. However, some parameters need to be specified during training, such as per_ device_ train_ batch_ size and per_ device_ eval_ batch_ size and other information. I can't find these parameters in the paper and project. Can you provide them?

**Comment by happygirlzt** [comment]
Hi, thank you for the interest in our work!
There should only be two hyper-parameters, i.e., `per_device_train_batch_size` and `per_device_eval_batch_size`. You can choose whatever suits your GPU size, such as 4 or 8. 
It should affect the performance too much. 
Please kindly let me know whether you have further concerns.
Thank you!

**Comment by YZS-web** [comment]
Thank you. At present, the value I set for these two parameters is 4. If I have any questions later, I will ask you again. Thank you

**Comment by happygirlzt** [comment]
Sure :)

**Comment by YZS-web** [comment]
Now I have reproduced the model on my computer, but the results are somewhat different. The paper uses the rouge score to measure the results, the rouge-1 score is 40.67, the rouge-2 score is 20.60, and the rouge-l score is 37.26. However, the model you provided, that is, the model trained for 66500 steps, the results after I run it are 36.05, 17.02 and 33.11. In addition, the results I obtained after training 66500 steps on my computer dropped further, being 34.36, 15.90 and 31.56 respectively. Do you know the reason or do you have any suggestions?

**Comment by happygirlzt** [comment]
Hmmm, it is weird. I am not sure how you calculate the rouge score, but maybe you want to use this script to calculate https://github.com/soarsmu/PRTiger/blob/main/src/calculate_rouge.py

**Comment by YZS-web** [comment]
Thank you, I will try after.

**Comment by happygirlzt** [comment]
No problem. Please keep me updated. Thanks :)
